name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.version == 'nightly' }}
    strategy:
      matrix:
        # NOTE: '1.0', ..., '1.4' fails.
        julia-version: ['1.5', '1', 'nightly']
        julia-arch: [x86]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      # Install julia (several versions).
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      # Build package.
      - uses: julia-actions/julia-buildpkg@latest
      # Run tests.
      - uses: julia-actions/julia-runtest@master
      # Get coverage.
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info
